name: yarn-spa-test
description: This GitHub Action will build and test your app
author: johnb8005
branding:
  icon: book-open
  color: purple
inputs:
  build-command:
    description: build command
    default: VITE_VERSION=${GITHUB_REF##*/} VITE_GIT_SHA=$GITHUB_SHA yarn build
  nodeversion:
    description: node version
    default: 20
  deploy-project-name:
    description: project name for the deploy service
  deploy-token:
    description: token needed to deploy
  message:
    description: The message to prepend the review suggestion
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeversion }}
    - name: Install dependencies via yarn
      run: yarn
      shell: bash
    - name: Test
      run: yarn test
      shell: bash
    - name: Build
      run: ${{ inputs.build-command }}
      shell: bash
    - name: Deploy
      run: |
        if [ -n "${{ inputs.deploy-project-name }}" ] && [ -n "${{ inputs.deploy-token }}" ]; then
          # create meta file
          printf "{\"sha\":\"$GITHUB_SHA\",\"version\":\"${GITHUB_REF##*/}\",\"date\":\"$(date -u)\"}" > dist/meta.json
          # zip build
          zip -r dist.zip dist
          # push to deploy service
          curl -k -X POST -H 'X-TOKEN: ${{ inputs.deploy-token }}' -F 'file=@dist.zip' -F 'project=${{ inputs.deploy-project-name }}' https://deploy.nexys.io/upload
          # remove created zip
          rm dist.zip
        else
          echo "not deploying, to deploy set 'deploy-project-name' and 'deploy-token'"
        fi
      shell: bash
